### ISSUE TITLE
Add @babel/plugin-syntax-dynamic-import

### ISSUE THREAD

**Issue by rdmurphy** [babel/preset-modules#11]
Hello! 👋

Bringing this up because [we tweeted a bit about it](https://twitter.com/_developit/status/1194819408067059712) when `preset-modules` was released. Is this something there's still interest in doing? I just noticed that `@babel/preset-env` has included it by default since `7.5.0` — so it may make sense to do it here too. I have a project that switches between `preset-env` and `preset-modules` and this would be one less plugin to install manually. 🙃

Thank you!

**Comment by nicolo-ribaudo** [comment]
Starting from Babel 7.8, the syntax plugin shouldn't be needed anymore 😉

**Comment by rdmurphy** [comment]
While I'm inclined to believe you because you are actually **with** Babel 😉 is there a reason why `preset-env` [still includes those plugins](https://github.com/babel/babel/blob/master/packages/babel-preset-env/package.json#L20-L28) in `7.8.*`? I had just assumed that because `preset-env` still had them that `preset-modules` would need them too. I just tested with `7.8` in a local project and it definitely gets mad if the plugins aren't available for `preset-module` to use.

**Comment by nicolo-ribaudo** [comment]
It's because it needs to be compatible with `@babel/parser@^7.0.0` (for backward compatibility), so we can't assume that the user is using `@babel/parser@^7.8.0`.
However, dyamic import in `@babel/preset-modules` never worked with `@babel/parser@7.0.0` so it's doesn't have this backward compatibility problem.

**Comment by rdmurphy** [comment]
@nicolo-ribaudo Makes sense. Thank you for explaining! 🙏 And I'll check on the `@babel/core` thing.
