### ISSUE TITLE
module/nomodule pattern output

### ISSUE THREAD

**Issue by SetiZ** [babel/preset-modules#16]
I wanted to use the module/nomodule pattern with then env modern/legacy, but I don't understand what's gonna be my output.
I tried it but it only output one file. What am I missing? What do I need to add to my babel or webpack configuration?

**Comment by nicolo-ribaudo** [comment]
You need two different Babel configurations, for example using an `env` variable:

```jsonc
{
  // default configuration, targeting browsers with modules support
  "presets": [
    ["@babel/preset-env", {
      "targets": { "esmodules": true },
      // This is the option to enable what was preset-modules, now that it's in preset-env
      "bugfixes": true
    }]
  ],

  // When compiling for old browsers, reove the "esmodules" target
  "env": {
    "nomodule": {
      "presets": ["@babel/preset-env"]
    }
  }
}
```

And then you call your build twice:
```
$ npm run build
$ BABEL_ENV=nomodule npm run build
```

**Comment by SetiZ** [comment]
I don't get it. Am I not supposed to use this ?
`{
  "presets": [
    "@babel/preset-modules"
  ]
}`
instead of preset-env?

I think I got it. I need to call the `BABEL_ENV=nomodule` for my old browsers

**Comment by nicolo-ribaudo** [comment]
> I don't get it. Am I not supposed to use this ?
> ```
> { "presets": [ "@babel/preset-modules" ] }
> ```
> 
> instead of preset-env?

Yeah sorry for not being clear; starting from Babel 7.9, `preset-modules` is not needed anymore if you enable the `"bugfixes": true` option in `preset-env`.

**Comment by SetiZ** [comment]
ok! so i don't need this package turns out! I'll stay with preset-env and add the BABEL_ENV. I was using two babelconfig files for module and no-module. I'll fix it to only one

**Comment by SetiZ** [comment]
got my answer thanks to @nicolo-ribaudo

**Comment by SetiZ** [comment]
I think I closed the issue too fast.
Can I do 
`"nomodule": {
      "presets": ["@babel/preset-env"]
    },
 "production: {...}`
If I am in production it will never go through the nomodule preset, right?

**Comment by nicolo-ribaudo** [comment]
Right, you would need something like `production-nomodule`.

**Comment by SetiZ** [comment]
ok so I will keep it separated for now. As it pass through CI, I need only one build.
