### ISSUE TITLE
LICENSE file

### ISSUE THREAD

**Issue by Bosch-Eli-Black** [babel/preset-modules#18]
Hello,

First off, thanks for sharing this project :)

I know that this `@babel/preset-modules` project already says that its code is MIT licensed, but could you please also add a LICENSE file containing the text of the MIT license?

My understanding is that this may be necessary in order for the code to be considered legally licensed under MIT.

Babel recently went through something similar: babel/babel#7308

**Comment by developit** [comment]
Added!
