### ISSUE TITLE
how to properly target compatible browsers

### ISSUE THREAD

**Issue by rbenzazon** [babel/preset-modules#29]
Hi,
Thanks for your contribution, this plugin is really useful.
I'm wondering if this plugin has any difference with the preset-env with esmodules set to true.
I would like to write a script that would target compatible browsers without using module/nomodule, because I read that this solution is not reliable and I need to avoid any double loading.
Is it possible to get the browser list compatible with this plugin and ideally it would be nice to ship with this plugin a function that returns true when compatible that we could use in the browser.
Regards

**Comment by developit** [comment]
This plugin is superceded by the new [bugfixes option](https://babeljs.io/docs/en/babel-preset-env#bugfixes) in preset-env, which can be enabled with the following config:

```
{
  targets: { esmodules:true },
  bugfixes: true
}
```

The `bugfixes` option uses the same plugins as `preset-modules`, but allows customization of the browser config.
