### ISSUE TITLE
Not working correctly with webpack-bundle-analyzer

### ISSUE THREAD

**Issue by Makio64** [babel/preset-modules#30]
When I user the preset-modules, the bundle analyzer plugin doesnt show the gzip size from the bundle compile by babel.

Works correctly with @babel/preset-env.

I opened an issue also on the webpack-bundle-analyzer repo
#https://github.com/webpack-contrib/webpack-bundle-analyzer/issues/440

**Comment by developit** [comment]
The best way to solve this is to switch from `@babel/preset-modules` to `@babel/preset-env` with the new `bugfixes:true` option. It's the same set of plugins, but you get to control the browser configuration:

```diff
{
  "presets": [
-    ["@babel/preset-modules"]
+    ["@babel/preset-env", {
+      "targets": {
+        "esmodules": true
+      },
+      "bugfixes": true
+    }]
  ]
}
```
