### ISSUE TITLE
Will your team update the deprecated package "@babel/plugin-proposal-unicode-property-regex"?

### ISSUE THREAD

**Issue by eunice-zhang** [babel/preset-modules#37]
### What is your Scenario?

When I install @babel/preset-env (3.6.2), npm will remind me to update this deprecated dependency: `@babel/plugin-proposal-unicode-property-regex`. 
When I checked the dependencyies tree, I found that `@babel/preset-env` depends on **@babel/preset-modules**, and **@babel/preset-modules** is dependent on **@babel/plugin-proposal-unicode-property-regex**.

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/97a9ca4a-98de-4ff0-998e-5f6acd4b6b11">

These deprecated packages are no longer maintained, which means that they will no longer receive any updates or fixes. Using plug-ins that are no longer maintained can present potential security and compatibility issues. 

So, will your team be updating the deprecated package in the future? Is there a plan?

### What are you suggesting?

`@babel/plugin-proposal-unicode-property-regex` should be used instead of `@babel/plugin-transform-unicode-property-regex`.

**Looking forward to your reply, thank you very much.** 💐

**Comment by nicolo-ribaudo** [comment]
I'll take a look :)

**Comment by nicolo-ribaudo** [comment]
The latest version of `@babel/preset-env` (7.25.4), as well as all the version released in the last year, depend on `@babel/preset-modules` version `0.1.6-no-external-plugins`. It has [no dependencies on other plugins](https://yarnpkg.com/package?q=%40babel%2Fpreset-modules&name=%40babel%2Fpreset-modules&version=0.1.6-no-external-plugins&file=%2Fpackage.json), including `@babel/plugin-proposal-unicode-property-regex`, so it should not cause any warning.

You can run `npx nls why @babel/plugin-proposal-unicode-property-regex` to see why you have that package.

**Comment by eunice-zhang** [comment]
Hi @nicolo-ribaudo, I really did not install the latest `@babel/preset-env` (7.25.4), I did not found its source code repository address, I mistakenly thought its latest version also used the latest version of `@babel/preset-modules` (0.1.6). 😂 
Anyway, thank you for your information sharing, I will upgrade `@babel/preset-env`, have a nice day. 👍
