### ISSUE TITLE
Unclear if it works with Node

### ISSUE THREAD

**Issue by oriSomething** [babel/preset-modules#8]
I'm not sure if I have an app that the code compiled both to Node (specifically Electron main thread) and modern browsers while using **Webpack** to compile will work well with what Node versions.
It's true I just test it locally, but I think it will be a good idea to write something about it in the readme.

**Comment by nicolo-ribaudo** [comment]
This preset shouldn't be used with Webpack: the only guarantee is that the compiled code will work if you are using native ECMAScript modules.

**Comment by developit** [comment]
It's okay to use with Webpack as long as you serve the result using `<script type=module>`. Regarding Node compatibility, none of the transforms here are necessary for V8, the engine Node runs on. That means `preset-env` with `targets.node` is already fairly well-optimized output for Node.

**Comment by oriSomething** [comment]
Maybe, it should be added (the explanation on Node) to the Readme?
